name: Build PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Gather Intelligence
        id: info
        run: |
          set -eEuo piefail
          echo ${{ github.repository }} | while IFS='/' read -r owner repository; do
              echo "::set-output name=owner::${owner}"
              echo "::set-output name=repository::${repository}"
          done
          
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Checkout Meta Repository
        run: |
          set -eEuo pipefail
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          readonly url=git@github.com:${{ steps.info.outputs.owner }}/actions.git
          git clone "${url}"
        
      - name: Install Dependencies
        run: |
          set -eEuo pipefail
          actions/bin/artifacts --include foo | while read -r submodule url; do
              echo "Downloading $url" >&2
              curl --fail $url | sudo tar -C / -xz --transform 's@include@usr/include@'
          done
        
      - name: Build
        run: |
          set -eEuo pipefail
          mkdir build && cd $_
          cmake -DCMAKE_INSTALL_PREFIX=install ..
          make -j$(nproc)
          make install
        
      - name: Upload artifacts
        run: |
          set -eEuo pipefail
          readonly dir=build/install
          readonly repo=${{ steps.info.outputs.repository }}
          readonly branch=$(echo ${{ github.head_ref }} | cut -d/ -f3)
          readonly file=${repo}-pr-${branch}.tar.gz
          tar -ca -C ${dir} -f ${file} .
          curl -Ffile=@${file} http://35.228.224.98/upload?token=29c0640d89c6f3ecd256
